version: '3.8'

services:
  dbmysql:
    container_name: users-mysqldb
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
    ports:
      - 3306:${DATABASE_PORT}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - usersnetwork

  nodeapi:
    container_name: users-api
    build: .
    depends_on:
      - dbmysql
    links:
      - dbmysql
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - usersnetwork

volumes:
  db-data:
  api:

networks:
  usersnetwork:
